services:
  - type: web
    name: codeigniter-app
    env: docker
    plan: free
    repo: https://github.com/aalesh01/banner-management-admin-portal
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CI_ENVIRONMENT
        value: production
