services:
  - type: web
    name: codeigniter-app
    env: docker
    plan: free
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_CODEIGNITER_REPO
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CI_ENVIRONMENT
        value: production
